// <auto-generated />
using System;
using BankOfDad.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankOfDad.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BankOfDadDbContext))]
    [Migration("20261001211551_RemoveLegacyAppleRefreshToken")]
    partial class RemoveLegacyAppleRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankOfDad.Domain.Entities.AppleRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_AppleRefreshTokens_UserId_RevokedAt");

                    b.ToTable("AppleRefreshTokens");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FirstDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("LateFeeFlat")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("LateFeeGraceDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LateFeePercent")
                        .HasColumnType("numeric(9,6)");

                    b.Property<bool>("SendReceipts")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendReminders")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("CreatedByParentId");

                    b.HasIndex("FamilyId", "Status");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillId", "DueDate")
                        .IsUnique();

                    b.HasIndex("BillId", "Seq")
                        .IsUnique();

                    b.ToTable("BillCharges");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillLateFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("WaivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WaivedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId")
                        .IsUnique();

                    b.HasIndex("BillId", "AssessedAt");

                    b.ToTable("BillLateFees");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ReceiptSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("BillId", "CreatedAt");

                    b.ToTable("BillPayments");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillPaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ChargeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LateFeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.HasIndex("LateFeeId");

                    b.HasIndex("PaymentId");

                    b.ToTable("BillPaymentAllocations");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApnsToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApnsToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.FamilyInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("FamilyId");

                    b.ToTable("FamilyInvites");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Installment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestDue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("InterestPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrincipalDue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrincipalPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoanId", "Seq")
                        .IsUnique();

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.LateFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstallmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("WaivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WaivedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstallmentId")
                        .IsUnique();

                    b.HasIndex("LoanId", "AssessedAt");

                    b.ToTable("LateFees");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualRate")
                        .HasColumnType("numeric(9,6)");

                    b.Property<Guid>("BorrowerChildId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FirstDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer");

                    b.Property<bool>("InterestEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LateFeeFlat")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("LateFeeGraceDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LateFeePercent")
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset?>("PaidOffAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Principal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("SendReceipts")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendReminders")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerChildId");

                    b.HasIndex("CreatedByParentId");

                    b.HasIndex("FamilyId", "Status");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PushedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.PairingCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildUserId");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("PairingCodes");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ReceiptSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("LoanId", "CreatedAt");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("InstallmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LateFeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("InstallmentId");

                    b.HasIndex("LateFeeId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentAllocations");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppleDeletionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppleSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AvatarColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AppleSubject")
                        .IsUnique()
                        .HasFilter("\"AppleSubject\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("FamilyId", "Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.AppleRefreshToken", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Bill", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.User", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.User", "CreatedByParent")
                        .WithMany()
                        .HasForeignKey("CreatedByParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("CreatedByParent");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillCharge", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Bill", "Bill")
                        .WithMany("Charges")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillLateFee", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Bill", "Bill")
                        .WithMany("LateFees")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.BillCharge", "Charge")
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Charge");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillPayment", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillPaymentAllocation", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.BillCharge", "Charge")
                        .WithMany()
                        .HasForeignKey("ChargeId");

                    b.HasOne("BankOfDad.Domain.Entities.BillLateFee", "LateFee")
                        .WithMany()
                        .HasForeignKey("LateFeeId");

                    b.HasOne("BankOfDad.Domain.Entities.BillPayment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charge");

                    b.Navigation("LateFee");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.FamilyInvite", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Installment", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Loan", "Loan")
                        .WithMany("Installments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.LateFee", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Installment", "Installment")
                        .WithMany()
                        .HasForeignKey("InstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.Loan", "Loan")
                        .WithMany("LateFees")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installment");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Loan", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.User", "BorrowerChild")
                        .WithMany()
                        .HasForeignKey("BorrowerChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.User", "CreatedByParent")
                        .WithMany()
                        .HasForeignKey("CreatedByParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowerChild");

                    b.Navigation("CreatedByParent");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.PairingCode", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.User", "ChildUser")
                        .WithMany()
                        .HasForeignKey("ChildUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildUser");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Payment", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Loan", "Loan")
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankOfDad.Domain.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Installment", "Installment")
                        .WithMany()
                        .HasForeignKey("InstallmentId");

                    b.HasOne("BankOfDad.Domain.Entities.LateFee", "LateFee")
                        .WithMany()
                        .HasForeignKey("LateFeeId");

                    b.HasOne("BankOfDad.Domain.Entities.Payment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installment");

                    b.Navigation("LateFee");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.User", b =>
                {
                    b.HasOne("BankOfDad.Domain.Entities.Family", "Family")
                        .WithMany("Users")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("LateFees");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.BillPayment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Family", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Loan", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("LateFees");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BankOfDad.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
